### ISSUE TITLE
check if current allowance implementation works around known erc20 frontrunning issues

### ISSUE THREAD

**Issue by thepiwo** [mradkov/aeternity-fungible-token#10]
https://blog.smartdec.net/erc20-approve-issue-in-simple-words-a41aaf47bca6

**Comment by thepiwo** [comment]
should be solved by having `change_allowance` instead of overwriting it. Do you agree @mradkov, then feel free to close the issue?

**Comment by mradkov** [comment]
This should be solved using the current implementation in the `change_allowance` entrypoint we currently have.

https://github.com/mradkov/aeternity-fungible-token/blob/b45e3a80c8334147e0c68dffab8d9367b4b4b3bd/contracts/extensions/allowances.aes#L113-L118

We are changing the allowance by the `value` being passed as an argument from the user.

So in this case, we won't have this issue.
