### ISSUE TITLE
Allow for swap from remote contract

### ISSUE THREAD

**Issue by thepiwo** [mradkov/aeternity-fungible-token#13]
- (option 1) provide example to allow for token swaps using burn calls from a remote interface in the new contract
 - (option 2) burn and add to burn event state, add claim function to be called by remote contract

**Comment by mradkov** [comment]
We can implement something like `migrate_and_burn` function which can only be called by a predefined caller (eg. the owner of the contract or the new contract address) which will pass the balances to the new token contract, update the state meta in order for it to address the changes in the contract `new_token_address` or something like this.

Maybe we should implement `private function locked() : bool` as well which can be used to lock the contract during the migration phase. 

```
record meta_info = { 
...
new_token_address: address
...
 }
```

**Comment by thepiwo** [comment]
![IMG_20191118_182410](https://user-images.githubusercontent.com/6539235/69070566-06ae8f80-0a31-11ea-9a14-ecc18609b3f1.jpg)

**Comment by thepiwo** [comment]
replaced by #23
