### ISSUE TITLE
Consider adding version/extensions indicator

### ISSUE THREAD

**Issue by thepiwo** [mradkov/aeternity-fungible-token#16]

**Comment by thepiwo** [comment]
we want to include an hardcoded entrypoint to indicate specific implemented extensions `  entrypoint aex9_extensions() : list(string) = ["swappable", "mintable"]
`

**Comment by mradkov** [comment]
As discussed we, agree to have an entrypoint which is defining what extensions a token is using so it can be easily interfaced later.

```sophia
entrypoint aex9_extensions() : list(string) = ["swappable", "mintable", "burnable"]
```
