### ISSUE TITLE
migration to native tokens

### ISSUE THREAD

**Issue by thepiwo** [mradkov/aeternity-fungible-token#23]

**Comment by mradkov** [comment]
We should return the `int` amount of burned tokens, so it's easier for migration paths implementations to get it.

**Comment by thepiwo** [comment]
![IMG_20191118_182410](https://user-images.githubusercontent.com/6539235/69071496-afa9ba00-0a32-11ea-9de8-34ef561d56ae.jpg)

**Comment by thepiwo** [comment]
![IMG_20191118_184057](https://user-images.githubusercontent.com/6539235/69071691-01eadb00-0a33-11ea-897e-a805f42fa62b.jpg)

**Comment by thepiwo** [comment]
## Version 1 (Doesn't support Contract owned tokens)
1. USER calls Native Token `mint`
2. Mint calls `swap` on AEX-9
3. AEX-9 burns for `Call.origin` Account, returns amount burned
4. Native Token mints tokens based on return value for `Call.origin`

## Version 2 (Supports Contract owned tokens, more complicated)
1. Contract/User calls AEX-9 `swap`
2. AEX-9 burns full amount and keeps track of `Call.caller` and amount
3. Contract/User calls Native Token `mint`
4. Mint calls `check_swap` with argument `Call.caller` on AEX-9
5. AEX-9 returns amount of tokens for argument account
6. Native Tokens marks `Call.caller` as migrated, keeps from migrating more for account

**Comment by thepiwo** [comment]
We did choose Version 2 to be implemented to have better support for all possible cases
