### ISSUE TITLE
Wrong interface for AEX-9

### ISSUE THREAD

**Issue by kraikov** [mradkov/aeternity-fungible-token#51]
The interface declaration is not entirely correct as the `stateful` modifier is missing, therefore when trying to use it to call an existing contract, the transaction is not being send as the function is considered static.

https://github.com/mradkov/aeternity-fungible-token/blob/master/contracts/fungible-token-full-interface.aes

**Comment by kraikov** [comment]
https://github.com/mradkov/aeternity-fungible-token/pull/52

**Comment by mradkov** [comment]
Thanks! Closing this as your PR #52 is already merged.
