### ISSUE TITLE
Balance interface lacks paging

### ISSUE THREAD

**Issue by Lfh2msn** [mradkov/aeternity-fungible-token#63]
there is a problem with balances, it does not support paging. With thousands or even tens of thousands of accounts, it is impossible to obtain all accounts.

**Comment by mradkov** [comment]
Use `entrypoint balance : (address) => option(int)` instead?

**Comment by mradkov** [comment]
Furthermore, this is only a reference implementation on the AEX9 standard, where we never specify in the interface any pagination of sorts.

I'm closing this issue, please re-open it if you think this topic needs further discussion :)
