### ISSUE TITLE
consider adding a transfer payload/identifier

### ISSUE THREAD

**Issue by thepiwo** [mradkov/aeternity-fungible-token#9]

**Comment by mradkov** [comment]
Can you clarify/extend your idea?

From what I understand you mean something like this:

```solidity
stateful entrypoint transfer(to_account: address, value: int, payload: option(string))
```

I assume the use-cases of this would be for example to specify payment reason e.g. invoice number?

**Comment by thepiwo** [comment]
I think this was proposed by robert and we were just opening as issue, to not forget about it.

His idea was that a transfer payload as described by you can be used for various things, e.g. legal requirement in some cases.

I think afterwards Robert was working on a separate token standard that focuses more on legal compliance, so I don't know if we should still include this here

**Comment by thepiwo** [comment]
to implement a basic fungible token contract we won't need this and save on gas costs for users in default situations.
